<aside id="sidebar" role="navigation">
  <div class="inner">
    {{ doc_sidebar('sidebar') }}
  </div>
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <ins class="adsbygoogle"
      style="display:block"
      data-ad-client="ca-pub-5061364613986259"
      data-ad-slot="9593020197"
      data-ad-format="auto"></ins>
  <script>
  (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</aside>
